### ISSUE TITLE
[Question] Tank Pellets Sensor

### ISSUE THREAD

**Issue by jonathannaguin** [algra4/ha-edilkamin#5]
Hello,

Thanks for this project, seems really promising!

One question though, with this integration, will it be possible to detect when the pellet tank is empty and alarm on it? One of the annoying issues with The Mind app is that you can run out of pellets and not get notified about it.

**Comment by algra4** [comment]
> Hello,
> 
> 
> 
> Thanks for this project, seems really promising!
> 
> 
> 
> One question though, with this integration, will it be possible to detect when the pellet tank is empty and alarm on it? One of the annoying issues with The Mind app is that you can run out of pellets and not get notified about it.

Hello,

Of course, for example in HA I created this automation :

```yaml
alias: Réservoir vide
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.edilkamin_tank_binary_sensor
    from: "off"
    to: "on"
condition: []
action:
  - service: notify.channel_maison
    data:
      title: 🔥 Pellet 🔥
      message: Réservoir presque vide, il faut lui donner à manger
mode: single

````
